### ISSUE TITLE
Export Bilkent Telephone Directory to Email Client

### ISSUE THREAD

**Issue by matifali** [furkankose/bilkent-scheduler#1]
Can you also make something to export Bilkent's online [telephone directory](https://www.bilkent.edu.tr/phonedir/) to Microsoft Outlook.

**Comment by furkankose** [comment]
I think, that is not directly related with the scheduler. That's why, I am not planning to include it to scheduler's scope.

**Comment by matifali** [comment]
OK.  I can work on a telephone directory export script to make it useable for Microsft Outlook and other email clients.
